<#
.SYNOPSIS
    Fills every SETME10 sentinel by reading the names Azure actually assigned,
    once the dev stack exists.

.DESCRIPTION
    WHY THESE NAMES COULD NOT SIMPLY BE EDITED.

    main.bicep derives resource names from

        resourceToken = uniqueString(subscription().id, environmentName, location)

    so the registry, SQL server, Service Bus namespace, Log Analytics workspace
    and Container Apps environment are all named after a hash of the
    SUBSCRIPTION ID. Change the subscription and every one of those names
    changes with it. The token cannot be computed offline -- uniqueString is an
    ARM function, not a documented algorithm -- so the only honest way to learn
    the new names is to deploy dev and then ask.

    The Container Apps environment's DEFAULT DOMAIN is worse still: it is
    generated by the platform, it is not
    derived from anything you control, and every application URL contains it.

    So: deploy dev first, run this, and it rewrites the hardcoded defaults in
    the scripts and the README that referred to the old subscription's names.

    IT REFUSES TO GUESS. If a resource is missing it says which one and changes
    nothing, rather than writing a half-correct set of names that fails later in
    a place unrelated to the cause.

.EXAMPLE
    ./migration/10-refresh-derived-names.ps1 -WhatIf
    ./migration/10-refresh-derived-names.ps1
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $SubscriptionId = '33c82ead-36a8-4d8f-b969-d8476690c224',
    [string] $ResourceGroup  = 'thinkschool-dev-rg'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# ---------------------------------------------------------------------------
# WHY NATIVE az CALLS GO THROUGH A HELPER.
#
# Windows PowerShell 5.1 turns anything a native command writes to STDERR into
# an ErrorRecord. With $ErrorActionPreference = 'Stop' that record is
# TERMINATING -- so `az` printing a harmless notice ("WARNING: The behavior of
# this command has been altered by the following extension: containerapp")
# kills the script, reported as NativeCommandError against the PowerShell line
# rather than as anything about az. `2>$null` does not help: the redirection
# still creates the record first.
#
# So: stderr is merged, ErrorRecords are filtered out, --only-show-errors keeps
# az quiet, and $LASTEXITCODE is what decides whether a call worked.
#
# The argument list is passed as an ARRAY, not as loose arguments: otherwise
# PowerShell tries to bind `-o` as a parameter name and fails with "the
# parameter name 'o' is ambiguous", because -OutVariable and -OutBuffer exist.
# ---------------------------------------------------------------------------
function Invoke-Az {
    param([Parameter(Mandatory)] [string[]] $AzArgs)
    $previous = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $out = & az @AzArgs --only-show-errors 2>&1 |
               Where-Object { $_ -isnot [System.Management.Automation.ErrorRecord] }
        return (($out | ForEach-Object { $_.ToString() }) -join [Environment]::NewLine)
    } finally {
        $ErrorActionPreference = $previous
    }
}

function Invoke-AzJson {
    param([Parameter(Mandatory)] [string[]] $AzArgs)
    $raw = Invoke-Az $AzArgs
    if ([string]::IsNullOrWhiteSpace($raw)) { return $null }
    if ($raw.Trim() -eq '[]' -or $raw.Trim() -eq 'null') { return $null }
    try { return ($raw | ConvertFrom-Json) } catch { return $null }
}

function Ok   ([string] $m) { Write-Host "  OK    $m" -ForegroundColor Green }
function Note ([string] $m) { Write-Host "  note  $m" -ForegroundColor Yellow }
function Die  ([string] $m) { Write-Host "  FAIL  $m" -ForegroundColor Red; exit 1 }

Invoke-Az @('account','set','--subscription',$SubscriptionId) | Out-Null

if ((Invoke-Az @('group','exists','--name',$ResourceGroup)).Trim() -ne 'true') {
    Die "Resource group $ResourceGroup does not exist. Deploy dev first (migration/README.md step 5)."
}

Write-Host 'Discovering what Azure named things:' -ForegroundColor Cyan

$acr = Invoke-AzJson @('acr','list','-g',$ResourceGroup,'--query','[0].{name:name,server:loginServer}','-o','json')
if ($null -eq $acr) { Die "No container registry in $ResourceGroup." }
Ok "registry        $($acr.name)  ($($acr.server))"

$sql = Invoke-AzJson @('sql','server','list','-g',$ResourceGroup,'--query','[0].{name:name,fqdn:fullyQualifiedDomainName}','-o','json')
if ($null -eq $sql) { Die "No SQL server in $ResourceGroup." }
Ok "sql server      $($sql.name)  ($($sql.fqdn))"

$sb = (Invoke-Az @('servicebus','namespace','list','-g',$ResourceGroup,'--query','[0].name','-o','tsv')).Trim()
if ([string]::IsNullOrWhiteSpace($sb)) { Die "No Service Bus namespace in $ResourceGroup." }
Ok "service bus     $sb"

$law = (Invoke-Az @('monitor','log-analytics','workspace','list','-g',$ResourceGroup,'--query','[0].name','-o','tsv')).Trim()
if ([string]::IsNullOrWhiteSpace($law)) { Die "No Log Analytics workspace in $ResourceGroup." }
Ok "log analytics   $law"

$cae = Invoke-AzJson @('containerapp','env','list','-g',$ResourceGroup,'--query','[0].{name:name,domain:properties.defaultDomain}','-o','json')
if ($null -eq $cae) { Die "No Container Apps environment in $ResourceGroup." }
Ok "container env   $($cae.name)"
Ok "default domain  $($cae.domain)"

# ---------------------------------------------------------------------------
# The token is the registry name minus its 'cr' prefix -- that is how
# modules/registry.bicep builds it, so reading it back is exact rather than
# inferred. The default domain is taken whole: it is not derived from anything.
# ---------------------------------------------------------------------------
if ($acr.name -notmatch '^cr(.+)$') { Die "Registry name '$($acr.name)' is not cr<token>; cannot derive the token safely." }
$token = $Matches[1]

# The domain is 'xxxx-yyyy.<region>.azurecontainerapps.io'; the sentinel stands
# for only the first label, because the region is already written out in the
# strings that contain it.
$domainLabel = ($cae.domain -split '\.')[0]

Write-Host ''
Write-Host "resource token : $token" -ForegroundColor Cyan
Write-Host "domain label   : $domainLabel" -ForegroundColor Cyan
Write-Host ''

$repoRoot = Split-Path -Parent $PSScriptRoot
$targets = @(
    'README.md',
    'Day7/piece2/infra/main.prod.bicepparam',
    'Day24/scripts/03-apply-sql-migrations.ps1',
    'Day24/scripts/04-finish-dev.ps1',
    'Day24/scripts/05-promote-prod.ps1',
    'Day25/scripts/02-entra-app-registrations.ps1',
    'Day26/scripts/01-github-oidc.ps1',
    'Day26/scripts/02-verify-telemetry.ps1',
    'Day29/scripts/00-provision-servicebus-topology.ps1',
    'Day29/scripts/run-host.ps1',
    'Day32/scripts/02-deploy.ps1'
)

$touched = 0
foreach ($rel in $targets) {
    $path = Join-Path $repoRoot $rel
    if (-not (Test-Path $path)) { Note "missing, skipped: $rel"; continue }

    $content = Get-Content -Path $path -Raw
    $before  = $content

    # ORDER MATTERS. 'SETME10-cae-domain' contains 'SETME10', so the longer
    # sentinel is replaced first; the other way round leaves '<token>-cae-domain'.
    $content = $content.Replace('SETME10-cae-domain', $domainLabel)
    $content = $content.Replace('SETME10', $token)

    if ($content -ne $before) {
        if ($PSCmdlet.ShouldProcess($rel, 'rewrite derived names')) {
            Set-Content -Path $path -Value $content -NoNewline
        }
        Ok $rel
        $touched++
    }
}

Write-Host ''
if ($touched -eq 0) {
    Note 'Nothing contained a SETME10 sentinel. Either this has already run, or the'
    Note 'files moved. migration/90-verify-no-old-ids.ps1 will say which.'
} else {
    Write-Host "$touched file(s) rewritten." -ForegroundColor Green
}
Write-Host ''
Write-Host 'Next:' -ForegroundColor Cyan
Write-Host '  1. git diff'
Write-Host '  2. ./migration/90-verify-no-old-ids.ps1'
Write-Host ''
