// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesPlatform.Modules.Curation.Infrastructure;

#nullable disable

namespace QuotesPlatform.Modules.Curation.Infrastructure.Migrations
{
    [DbContext(typeof(CurationDbContext))]
    [Migration("20260915103939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("curation")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuotesPlatform.Modules.Curation.Domain.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Collections", "curation");
                });

            modelBuilder.Entity("QuotesPlatform.Modules.Curation.Domain.Collection", b =>
                {
                    b.OwnsMany("QuotesPlatform.Modules.Curation.Domain.CollectionItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("AddedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsPublishable")
                                .HasColumnType("bit");

                            b1.Property<int>("Position")
                                .HasColumnType("int");

                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("Id");

                            b1.HasIndex("CollectionId", "QuoteId")
                                .IsUnique();

                            b1.ToTable("CollectionItems", "curation");

                            b1.WithOwner()
                                .HasForeignKey("CollectionId");
                        });

                    b.OwnsMany("QuotesPlatform.Modules.Curation.Domain.CollectionMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("CollectionId", "UserId")
                                .IsUnique();

                            b1.ToTable("CollectionMembers", "curation");

                            b1.WithOwner()
                                .HasForeignKey("CollectionId");
                        });

                    b.Navigation("Items");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
