env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://quotes-api-dev.greenhill-88fb93d9.uaenorth.azurecontainerapps.io/health
    - https://quotes-api-dev.greenhill-88fb93d9.uaenorth.azurecontainerapps.io/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://quotes-api-dev.greenhill-88fb93d9.uaenorth.azurecontainerapps.io/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-api-final.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
